In [2]:
import sys, os
import matplotlib
import matplotlib.pyplot as plt

import cv2
import numpy as np

import createPCAModel

%matplotlib qt

In [3]:
test = r'D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖'
#test = r'D:\home\migichen\project\Flare\EigenAnalysis\images\P1\pool'
aligned = 'images/flare_lp17b9607_zero/align'

pca = createPCAModel.PCAModel()
pca.JITTER = False
pca.SHRINK=True
pca.MASK_RAD=10
pca.REMOVE_BORDER=False

images = pca.readImages(test)


Reading images from D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖 ... Reading images from D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖 ... 
Reading images from D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\NG ... 
Reading 0 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\NG\0023_20190719_023539_861#FNG.png
Reading 1 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\NG\0200_20190719_030500_611#FNG.png
Reading 2 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\NG\0519_20190719_035922_263#FNG.png
Reading 3 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\NG\0581_20190719_040811_356#FNG.png
Reading 4 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\NG\0617_20190719_041259_654#FNG.png
Reading images from D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK ... 
Reading 5 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0000_20190719_023301_355#OK.png
Reading 6 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0006_20190719_023311_040#OK.png
Reading 7 D:\I

Reading 82 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0092_20190719_024746_907#OK.png
Reading 83 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0093_20190719_024756_224#OK.png
Reading 84 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0094_20190719_024804_720#OK.png
Reading 85 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0095_20190719_024814_475#OK.png
Reading 86 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0096_20190719_024823_656#OK.png
Reading 87 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0097_20190719_024832_241#OK.png
Reading 88 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0098_20190719_024841_506#OK.png
Reading 89 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0099_20190719_024851_702#OK.png
Reading 90 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0100_20190719_024904_628#OK.png
Reading 91 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0101_20190719_024917_793#OK.png
Reading 92 D:\Images\8534\LP17

Reading 169 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0201_20190719_030510_509#OK.png
Reading 170 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0202_20190719_030520_104#OK.png
Reading 171 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0203_20190719_030530_280#OK.png
Reading 172 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0204_20190719_030539_813#OK.png
Reading 173 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0205_20190719_030549_662#OK.png
Reading 174 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0206_20190719_030558_920#OK.png
Reading 175 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0207_20190719_030611_589#OK.png
Reading 176 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0208_20190719_030621_026#OK.png
Reading 177 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0209_20190719_030630_412#OK.png
Reading 178 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0210_20190719_030643_197#OK.png
Reading 179 D:\Image

Reading 257 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0298_20190719_031943_637#OK.png
Reading 258 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0299_20190719_031954_874#OK.png
Reading 259 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0300_20190719_032007_784#OK.png
Reading 260 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0301_20190719_032017_242#OK.png
Reading 261 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0302_20190719_032026_546#OK.png
Reading 262 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0303_20190719_032035_809#OK.png
Reading 263 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0304_20190719_032044_997#OK.png
Reading 264 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0305_20190719_032057_716#OK.png
Reading 265 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0306_20190719_032107_586#OK.png
Reading 266 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0308_20190719_032116_773#OK.png
Reading 267 D:\Image

Reading 346 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0393_20190719_034342_468#OK.png
Reading 347 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0394_20190719_034350_886#OK.png
Reading 348 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0395_20190719_034400_579#OK.png
Reading 349 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0396_20190719_034413_097#OK.png
Reading 350 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0397_20190719_034422_351#OK.png
Reading 351 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0398_20190719_034432_070#OK.png
Reading 352 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0399_20190719_034441_257#OK.png
Reading 353 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0400_20190719_034449_657#OK.png
Reading 354 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0401_20190719_034459_441#OK.png
Reading 355 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0402_20190719_034508_694#OK.png
Reading 356 D:\Image

Reading 434 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0513_20190719_035817_876#OK.png
Reading 435 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0514_20190719_035828_005#OK.png
Reading 436 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0515_20190719_035837_721#OK.png
Reading 437 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0516_20190719_035847_639#OK.png
Reading 438 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0517_20190719_035900_949#OK.png
Reading 439 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0518_20190719_035910_480#OK.png
Reading 440 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0521_20190719_035932_316#OK.png
Reading 441 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0522_20190719_035940_852#OK.png
Reading 442 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0523_20190719_035958_508#OK.png
Reading 443 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0524_20190719_040010_997#OK.png
Reading 444 D:\Image

Reading 519 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0621_20190719_041338_497#OK.png
Reading 520 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0622_20190719_041350_158#OK.png
Reading 521 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0623_20190719_041359_364#OK.png
Reading 522 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0624_20190719_041409_322#OK.png
Reading 523 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0625_20190719_041419_379#OK.png
Reading 524 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0626_20190719_041428_843#OK.png
Reading 525 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0627_20190719_041441_620#OK.png
Reading 526 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0628_20190719_041451_404#OK.png
Reading 527 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0629_20190719_041459_982#OK.png
Reading 528 D:\Images\8534\LP17B9607\0719\來料盤1ACCJ170694_F\原始圖\OK\0630_20190719_041513_469#OK.png
Reading 529 D:\Image

In [ ]:
# Using align.py
base_image = images[-1]
ali = align.AlignImage()
ali.set_base(base_image)

for i in range(len(images)):
    print (i)
    cv2.imshow('image', (images[i] - base_image+.5))
    out, offset = ali.align_image(images[i])
    cv2.imshow('aligned', (out - base_image+.5))
    k = cv2.waitKey(0)
    if k==27: break
print ('done')

In [ ]:
# Original implementation with optical flow
base_image = images[-1]


def createCircleMask(height, width, rad):
    # rad: ratio from half of height
    circle = np.zeros((height,width))
    skip_circle = cv2.circle(
      circle,(int(width/2),int(height/2)),
      int(height*.5*rad),1,thickness=-1)
    return circle

def align_image(im, base, max_offset=5, mask_rad=1):
    # Optical flow using Lucas–Kanade method
    # max_offset:
    #   blurring to cover possible offset. Must be odd value, or 0
    # mask_rad:
    #   radius of mask circle over height
    height, width = base_image.shape
    
    if max_offset==0:
        imb = im
        baseb = base
    else:
        imb = cv2.GaussianBlur(im, (max_offset, max_offset), 0)
        baseb = cv2.GaussianBlur(base, (max_offset, max_offset), 0)
    
    dx = cv2.Sobel(baseb,cv2.CV_16S,1,0,ksize=3)/8. # 8: normalize
    dy = cv2.Sobel(baseb,cv2.CV_16S,0,1,ksize=3)/8.
    b = (imb-baseb)
    
    del imb
    del baseb
    
    # mask
    mask = createCircleMask(height, width, mask_rad)
    dx = dx[mask>0].flatten()
    dy = dy[mask>0].flatten()
    b = b[mask>0].flatten()
    
    #Lucas–Kanade method
    A = np.stack([dx, dy]).T
    try:
        invATA = np.linalg.inv(np.dot(A.T, A))
    except:
        print ("Cannot compute inverse matrix! Skip align.")
        return im, [0,0]
    ATb = np.dot(A.T, b)
    v = np.dot(invATA, ATb)*1.5 #why 1.5 gets best alignment?
    
    H = np.float32([[1, 0, v[0]],
                    [0, 1, v[1]]])
    out = cv2.warpAffine(im, H, (width, height))
    return out, v
     
for i in range(len(images)):
    temp = images[i]
    cv2.imshow('image', (temp - base_image+.5))
    for _ in range(0,3): # no more than 3 times
        out, v = align_image(temp, base_image)
        cv2.imshow('aligned', (out - base_image+.5))
        temp = out
        print (i, v)
        k = cv2.waitKey(0)
        if k==27: break
        if np.all(np.abs(v)<1): break
    if k==27:break    
    
print ('Done')                     

In [85]:
# Pointwise optical flow
base_image = images[-1]
test_image = images[30]
#base_im = cv2.resize(base_image, None, fx=.25, fy=.25)
#test_im = cv2.resize(test_image, None, fx=.25, fy=.25)
base_im = base_image*255.
test_im = test_image*255.
cv2.imshow('result', base_im)

flow = cv2.calcOpticalFlowFarneback(test_im, base_im,None, 
                                    pyr_scale=0.5, 
                                    levels=3, 
                                    winsize=15, 
                                    iterations=5, 
                                    poly_n=5, 
                                    poly_sigma=1.5, flags=0)
#                                   None, 0.5, 5, 15, 3, 5, 1.5, 0)
#flow = cv2.calcOpticalFlowFarneback(test_im, base_im, None, 0.5, 3, 15, 3, 5, 1.5, 0)
#      flow = cv2.calcOpticalFlowFarneback(prvs,next, None, 0.5, 3, 15, 3, 5, 1.2, 0)


hsv = np.zeros(base_im.shape+(3,)).astype(np.uint8)
hsv[...,1] = 255
mag, ang = cv2.cartToPolar(flow[...,0], flow[...,1])
hsv[...,0] = ang*180/np.pi/2
hsv[...,2] = cv2.normalize(mag,None,0,255,cv2.NORM_MINMAX)
bgr = cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR)

print (np.mean(mag))
cv2.imshow('flow',bgr)
flow.shape
print(np.mean(flow[...,0]))
print(np.mean(flow[...,1]))

1.408519
-1.2859595
-0.55548817


In [56]:
sz = base_im.shape
im_out = np.zeros(sz, dtype=np.float32)
print (im_out.shape)
for i in range(sz[0]):
    for j in range(sz[1]):
        i1 = int(i+flow[i,j,0])
        j1 = int(j+flow[i,j,1])
        if i1>=0 and j1>=0 and i1<sz[0] and j1<sz[1]:
            im_out[i1][j1] = test_im[i,j]
cv2.imshow('out', np.hstack((im_out, test_im-base_im+128, im_out-base_im+128))/255.)

(390, 526)


In [127]:
select = np.where((flow[...,0] + flow[...,1]).flatten()>.1)
print(len(select[0]))
ys, xs = np.meshgrid(range(sz[0]), range(sz[1]), indexing='ij')
xs1 = xs+flow[...,0]
ys1 = ys+flow[...,1]
xs = xs.flatten()[select[0]]
ys = ys.flatten()[select[0]]
xs1 = xs1.flatten()[select[0]]
ys1 = ys1.flatten()[select[0]]
M = np.vstack([xs, ys, np.ones(len(xs))]).T
invMTM = np.linalg.inv(M.T @ M)
MTbx = M.T @ xs1
MTby = M.T @ ys1
ax = invMTM @ MTbx
ay = invMTM @ MTby
H = np.vstack([ax, ay])
print (H)
print (np.max(M @ ax - xs1), np.mean(M @ ax - xs1))
print (np.max(M @ ay - ys1), np.mean(M @ ay - ys1))


im_out = cv2.warpAffine(test_im,H,(sz[1],sz[0]))
cv2.imshow('out1', np.hstack((im_out, test_im-base_im+128, im_out-base_im+128))/255.)

293
[[ 0.95833564 -0.01804995  6.69917321]
 [ 0.04239588  1.01944955 -6.59256137]]
0.5285772640017967 9.13811309519184e-13
0.9068462518853266 -7.108337430238927e-11


In [101]:
H = np.array([[1, 0, -2.29],[0,1,-1]], np.float)
im_out = cv2.warpAffine(test_im,H,(sz[1],sz[0]))
cv2.imshow('out1', np.hstack((im_out, test_im-base_im+128, im_out-base_im+128))/255.)

In [66]:
moved = np.where(np.any(np.reshape(flow, [-1,2]) > 1e-9, axis=1))
print (np.max(flow), moved)

i_coords, j_coords = np.meshgrid(range(base_im.shape[1]), range(base_im.shape[0]), sparse=False, indexing='ij')
coords = np.array([i_coords, j_coords]).T
new_coords = coords + flow

coords1 = np.array([coords[:,:,0].flatten()[moved], coords[:,:,1].flatten()[moved]])
new_coords1 = np.array([new_coords[:,:,0].flatten()[moved], new_coords[:,:,1].flatten()[moved]])

'''
pts_src and pts_dst are numpy arrays of points
in source and destination images. We need at least 
4 corresponding points. 
'''
#h, status = cv2.findHomography(np.reshape(coords1, [-1,2]), 
#                               np.reshape(new_coords1, [-1,2]))
h, status = cv2.findHomography(np.vstack([xs,ys]).T, 
                               np.vstack([xs1,ys1]).T, cv2.RANSAC,5.0)
print (h)
''' 
The calculated homography can be used to warp 
the source image to destination. Size is the 
size (width,height) of im_dst
'''
 
im_out = cv2.warpPerspective(test_im, h, (base_im.shape[1], base_im.shape[0]))
cv2.imshow('out2', np.hstack([test_im-base_im+128, im_out-base_im+128])/255.)

1.9914634 (array([     0,      1,     17, ..., 205137, 205138, 205139], dtype=int64),)
[[ 9.59506728e-01 -3.12898260e-02  1.14025458e+01]
 [-1.27243941e+00  1.06653475e+00 -1.20540914e+01]
 [-3.47206493e-03  9.13624504e-05  1.00000000e+00]]
