In [154]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import os

%matplotlib notebook

In [7]:
def createCircleMask(height, width, rad):
    # rad: ratio from half of height
    circle = np.zeros((height,width))
    skip_circle = cv2.circle(
        circle,(int(width/2),int(height/2)),
        int(height*.5*rad),1,thickness=-1)
    return circle

In [2]:

## 读取图像，解决imread不能读取中文路径的问题
def cv_imread(filePath):
  try:
    cv_img=cv2.imdecode(np.fromfile(filePath,dtype=np.uint8),-1)
    ## imdecode读取的是rgb，如果后续需要opencv处理的话，需要转换成bgr，转换后图片颜色会变化
    ##cv_img=cv2.cvtColor(cv_img,cv2.COLOR_RGB2BGR)
    return cv_img
  except:
    traceback.print_exc()
    return None

In [342]:
MAX_FEATURES = 1000
GOOD_MATCH_PERCENT = .9 #0.15

def alignImagesPerspective(im1, im2, mask):
    # Convert images to grayscale
    #im1Gray = cv2.cvtColor(im1, cv2.COLOR_BGR2GRAY)
    #im2Gray = cv2.cvtColor(im2, cv2.COLOR_BGR2GRAY)
    im1Gray = im1
    im2Gray = im2

    # Detect ORB features and compute descriptors.
    orb = cv2.ORB_create(MAX_FEATURES)
    keypoints1, descriptors1 = orb.detectAndCompute(im1Gray, mask)
    keypoints2, descriptors2 = orb.detectAndCompute(im2Gray, mask)

    # Match features.
    matcher = cv2.DescriptorMatcher_create(cv2.DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING)
    #matcher = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
    matches = matcher.match(descriptors1, descriptors2, None)

    # Sort matches by score
    matches.sort(key=lambda x: x.distance, reverse=False)

    # Remove not so good matches
    numGoodMatches = int(len(matches) * GOOD_MATCH_PERCENT)
    matches = matches[:numGoodMatches]

    # Draw top matches
    imMatches = cv2.drawMatches(im1, keypoints1, im2, keypoints2, matches, None)
    cv2.imshow("matches.jpg", imMatches)

    # Extract location of good matches
    points1 = np.zeros((len(matches), 2), dtype=np.float32)
    points2 = np.zeros((len(matches), 2), dtype=np.float32)

    for i, match in enumerate(matches):
        points1[i, :] = keypoints1[match.queryIdx].pt
        points2[i, :] = keypoints2[match.trainIdx].pt

    points1 = np.expand_dims(points1, 0)
    points2 = np.expand_dims(points2, 0)

    # Find homography
    h, mask = cv2.findHomography(points1, points2, cv2.RANSAC, 10)
    assert h is not None
    
    print ('alignImagesPerspective')
    print (h)

    # Use homography
    height, width = im2.shape
    im1Reg = cv2.warpPerspective(im1, h, (width, height))

    return im1Reg, h

# !!!!!!!!!!!!!
def alignImagesPerspectiveMulti(im1, im2, mask):
    h = np.identity(3)
    imcur = im1
    sz = im1.shape
    maskcur = mask
    for i in range(15):
        _, h1 = alignImagesPerspective(imcur, im2, mask)
        if np.all(np.abs(h1 - np.identity(3)) < .05):
            break
        h = h1 @ h        
        imcur = cv2.warpAffine(im1,h[:2,:],(sz[1],sz[0]))
        maskcur = cv2.warpAffine(mask,h[:2,:],(sz[1],sz[0]))
        
        cv2.imshow('mask', maskcur)
        cv2.imshow('out', np.hstack((im2,im1,imcur,np.abs(imcur-im2)))/255.)
        cv2.waitKey(10)
    return imcur, h

In [123]:
def alignImagesAffine(im1, im2, mask):
    im1 = im1 * mask
    im2 = im2 * mask
    h = cv2.estimateRigidTransform(im2, im1, False)
    assert h is not None
    h = np.vstack((h, [[0,0,1]]))

    print ('alignImagesAffine:')
    print (h)

    # Use homography
    height, width = im2.shape
    im1Reg = cv2.warpPerspective(im1, h, (width, height))

    return im1Reg, h

In [490]:
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
RANSAC_TH = 5
def getFlow(im_transformed1, im1):
    '''
    output: 
        flow: size [height, width, 2] 
        flow[:,:,0] is x offset
        flow[:,:,1] is y offset
    '''
    # https://docs.opencv.org/3.4/d4/dee/tutorial_optical_flow.html
    flow = cv2.calcOpticalFlowFarneback(im_transformed1, im1 ,None, 
                                        pyr_scale=0.5, 
                                        levels=7, 
                                        winsize=15,  # 30 good
                                        iterations=20, 
                                        poly_n=5, 
                                        poly_sigma=1.1, flags=0)
    #                                   None, 0.5, 5, 15, 3, 5, 1.5, 0)
    return flow
def getH(flow, mask):
    sz = mask.shape
    flow[...,0] *= mask
    flow[...,1] *= mask
    # Image registration 
    # Ref: CS4243 Computer Vision and Pattern Recognition, NUS - Leow Wee Kheng
    select = np.where((np.abs(flow[...,0]) + np.abs(flow[...,1])).flatten()>1)

    i, j = np.meshgrid(range(sz[0]), range(sz[1]), indexing='ij')
    i1 = i+flow[...,1]
    j1 = j+flow[...,0]
    i = i.flatten()[select]
    j = j.flatten()[select]
    i1 = i1.flatten()[select]
    j1 = j1.flatten()[select]
    M = np.vstack([j,i, np.ones_like(j)]).T
    print (M.shape)
    bj = j1
    bi = i1
    aj = np.linalg.inv(M.T @ M) @ M.T @ bj
    ai = np.linalg.inv(M.T @ M) @ M.T @ bi
    H = np.vstack([aj.T, ai.T, [0,0,1]])
    print ('off=\n', H)
    return H

    #coords = np.vstack([xs, ys]).T
    #coords1 = np.vstack([xs1, ys1]).T
    #M = cv2.getAffineTransform(coords, coords1)
    #print (M)

def getH1(flow, mask):
    sz = mask.shape
    flow[...,0] *= mask
    flow[...,1] *= mask
    # Image registration 
    # Ref: CS4243 Computer Vision and Pattern Recognition, NUS - Leow Wee Kheng
    select = np.where((np.abs(flow[...,0]) + np.abs(flow[...,1])).flatten()>0.001)
    if (len(select[0])<3):
        return np.identity(3)
    i, j = np.meshgrid(range(sz[0]), range(sz[1]), indexing='ij')
    i1 = i+flow[...,1]
    j1 = j+flow[...,0]
    i = i.flatten()[select]
    j = j.flatten()[select]
    i1 = i1.flatten()[select]
    j1 = j1.flatten()[select]
    H, mask = cv2.findHomography(np.vstack([j,i]).T, np.vstack([j1,i1]).T,
                                 cv2.RANSAC, RANSAC_TH)
    print (H)
    return H
    
def showFlow(im_ori, im_transformed, flow, mask):
    flow[...,0] *= mask
    flow[...,1] *= mask
    
    sz = im_ori.shape
    im_out = np.zeros(sz, dtype=np.float32)
    print (im_out.shape)
    for i in range(sz[0]):
        for j in range(sz[1]):
            i1 = int(i+flow[i,j,1])
            j1 = int(j+flow[i,j,0])
            if i1>=0 and j1>=0 and i1<sz[0] and j1<sz[1]:
                im_out[i1][j1] = im_transformed[i,j]
    #plt.figure()
    #plt.imshow(np.hstack((im_ori, im_out)),  cmap='gray')    
    cv2.imshow('flow map', np.hstack((im_ori, im_out))/255.)
    
def showFlow1(im_ori, im_transformed, flow, mask):
    flow[...,0] *= mask
    flow[...,1] *= mask
    mag, ang = cv2.cartToPolar(flow[...,0], flow[...,1])
    hsv = np.zeros(im_ori.shape+(3,))
    hsv[...,0] = ang*180/np.pi
    hsv[...,1] = 255
    hsv[...,2] = mag/50 #cv2.normalize(mag,None,0,1,cv2.NORM_MINMAX)
    bgr = cv2.cvtColor(hsv.astype(np.float32),cv2.COLOR_HSV2RGB)
    cv2.imshow('flow', bgr)
    
def alignImagesOpticalFlow(im1, im2, mask):
    mask = np.float32(mask)
    im1 = np.float32(im1)
    im2 = np.float32(im2)
    imcur = im1
    sz = im1.shape
    
    H0 = np.identity(3)
    rads = 16
    
    best_h = H0
    best_err = 9999
    
    for r in range(0,rads):
        # rotate
        T_shift_neg = np.array([
            [1, 0, -sz[1]*.5],
            [0, 1, -sz[0]*.5],
            [0, 0, 1]])
        T_shift = np.array([
            [1, 0, sz[1]*.5],
            [0, 1, sz[0]*.5],
            [0, 0, 1]])
        th = np.pi/(rads/2)
        T_rotate = np.array([
            [np.cos(th), -np.sin(th), 0],
            [np.sin(th), np.cos(th), 0],
            [0, 0, 1]])
        H0 = T_shift @ T_rotate @ T_shift_neg @ H0
        H1 = H0
        #H1 = np.array([[1,0,10], [0,1,0], [0,0,1]], dtype=np.float)
        imcur = cv2.warpAffine(im1,H1[:2,:],(sz[1],sz[0]))
        mask = cv2.warpAffine(mask,H1[:2,:],(sz[1],sz[0]))
        cv2.imshow('mask', mask)

        mask1=mask

        for i in range(5):
            flow = getFlow(imcur, im2)

            showFlow1(im1, imcur, flow, mask1)        

            H = getH1(flow, mask1)
            
            H1 = H @ H1
            
            det = np.linalg.det(H1)
            print ("H1 Det:", det)
            if det>2 or det<.5:
                break
                
            imcur = cv2.warpAffine(im1,H1[:2,:],(sz[1],sz[0]))
            mask1 = cv2.warpAffine(mask,H1[:2,:],(sz[1],sz[0]))
            cv2.imshow('mask', mask1)
            
            err = np.mean(abs(imcur-im2)[mask.astype('bool')])
            if err < best_err:
                print ('best_err = ', best_err)
                best_err = err
                best_h = H1

            print (np.max(imcur), np.max(im2))
            print (np.max(np.abs(imcur-im2)))
            #plt.figure()
            print (im1.shape)
            #plt.imshow(np.hstack((im2,im1,imcur,np.abs(imcur-im2))) ,  cmap='gray')
            #plt.pause(.01)
            cv2.imshow('out', np.hstack((im2,im1,imcur*mask1,np.abs(imcur-im2)))/255.)
            k = cv2.waitKey(1)
            if k==32:
                break
    return best_h

In [ ]:

#refFilename = "D:/Images/A70/Image_60057B1/鏡筒_A_IPI_4_20180510_154021893.png"
#imFilename = "D:/Images/A70/Image_60057B1/鏡筒_A_IPI_4_20180510_154029071.png"
#mask_rad=.4
#refFilename = "D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040155115.png"
#imFilename = "D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040159422.png"
#mask_rad=.2

refFilename = "D:\Images\A70\Image_60057B1/鏡筒_A_IPI_4_20180510_154021893.png"
path = "D:\Images\A70\Image_60057B1/"
mask_rad=.4
#refFilename = "D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040155115.png"
#path = "D:\Images\A70\Image_8419A5/"
#mask_rad=.2

mask = 1-createCircleMask(im.shape[0], im.shape[1], mask_rad).astype('uint8')
mask *= createCircleMask(im.shape[0], im.shape[1], .8).astype('uint8')

step = 8

# Read reference image
print("Reading reference image : ", refFilename)
imReference = cv_imread(refFilename)
imReference = imReference[::step, ::step]
cv2.imshow('ref', imReference)

# Create array of array of images.
imagePaths = []
i = 0        
k = 0
for root, subdirs, files in os.walk(path):
    print("Reading images from " + root + " ... ", flush=True)      
    for filename in files:
        fileExt = os.path.splitext(filename)[1]
        if fileExt not in [".jpg", ".jpeg", ".png"]:
            continue

        imagePath = os.path.join(root, filename)
            
        # Read image to be aligned
        print("Reading image to align : ", imFilename);  
        im = cv_imread(imagePath)
        im = im[::step, ::step]
        cv2.imshow('im', im)

        if im is None :
            print("Error:{} not read properly".format(imagePath))
            continue
        
        #Reference *= mask
        #im *= mask
        
        print("Aligning images ...")
        # Registered image will be resotred in imReg. 
        # The estimated homography will be stored in h. 
        
        #imReg, h = alignImagesPerspectiveMulti(im, imReference, mask)
        #imReg, h = alignImagesAffine(imReg, imReference, mask)
        h = alignImagesOpticalFlow(im, imReference, mask)
        sz = imReference.shape
        imReg = cv2.warpAffine(im,h[:2,:],(sz[1],sz[0]))        
        
        
        diff = np.abs(imReg.astype('float')-imReference.astype('float')).astype('uint8')
        cv2.imshow('out', np.hstack([imReference, im, imReg, diff ]))

        # Write aligned image to disk. 
        #outFilename = "aligned.jpg"
        #print("Saving aligned image : ", outFilename); 
        #cv2.imwrite(outFilename, imReg)

        # Print estimated homography
        print("Estimated homography : \n",  h)
        print ('Press key to cont.')
        k = cv2.waitKey(0)

        if k==27:
            break
    if k==27:
        break
print ('Done')

Reading reference image :  D:\Images\A70\Image_60057B1/鏡筒_A_IPI_4_20180510_154021893.png
Reading images from D:\Images\A70\Image_60057B1/ ... 
Reading image to align :  D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040159422.png
Aligning images ...
[[ 1.07267117e+00  1.70644631e-01 -1.29639477e+01]
 [-8.96113856e-02  1.12376658e+00  6.81946416e+00]
 [ 1.07817969e-04  7.46492390e-04  1.00000000e+00]]
H1 Det: 1.2178265114611946
best_err =  9999
255.0 255.0
255.0
(150, 200)
[[ 1.11656964e+00  1.50778517e-01 -1.65557287e+01]
 [-9.53261455e-02  1.04256335e+00  1.09131211e+01]
 [ 8.16502170e-04  4.14526965e-04  1.00000000e+00]]
H1 Det: 1.448613745493979
255.0 255.0
255.0
(150, 200)
[[ 6.41335356e-01  7.60292079e-02  4.44292809e+00]
 [-2.59920401e-01  7.55283861e-01  2.36475976e+01]
 [-2.42330333e-03  2.14474640e-04  1.00000000e+00]]
H1 Det: 0.7307188895906864
255.0 255.0
255.0
(150, 200)
[[ 1.19498607e+00  1.84838520e-02 -5.65819205e+00]
 [ 9.26923374e-02  1.06995771e+00 -3.01221280e+00]
 [

[[ 8.94795506e-01  3.43287577e-02  2.43795975e+00]
 [-8.96808121e-02  1.02026498e+00  5.19807425e+00]
 [-5.99223915e-04  3.31925522e-04  1.00000000e+00]]
H1 Det: 0.9505057352656321
255.0 255.0
255.0
(150, 200)
[[ 1.26418829e+00  2.19492228e-01 -2.66749541e+01]
 [-3.62050370e-02  1.03847463e+00  8.50860751e+00]
 [ 2.61976736e-04  9.19843761e-04  1.00000000e+00]]
H1 Det: 1.254206209025451
255.0 255.0
255.0
(150, 200)
[[ 8.20370517e-01  7.78416205e-02  3.26343287e-01]
 [-1.39539618e-01  8.90441608e-01  1.70380181e+01]
 [-4.15179920e-04  1.97167630e-05  1.00000000e+00]]
H1 Det: 0.928924757443818
255.0 255.0
255.0
(150, 200)
[[ 1.02852320e+00  6.34684626e-03 -1.86838473e+00]
 [-5.85543403e-02  9.84452147e-01  6.30332225e+00]
 [-7.32612654e-05  2.90221439e-05  1.00000000e+00]]
H1 Det: 0.9406114172048693
255.0 255.0
255.0
(150, 200)
[[ 9.62609082e-01 -1.16854924e-02  1.57080855e+00]
 [-1.57857041e-02  9.77406869e-01  1.50735725e+00]
 [-1.83453751e-04 -4.52631388e-05  1.00000000e+00]]
H1 Det: 

255.0 255.0
255.0
(150, 200)
[[ 1.44240452e+00 -2.17249450e-01 -1.86947772e+01]
 [ 2.64852720e-01  9.90371979e-01 -1.95786088e+01]
 [ 1.64808110e-03 -1.81101385e-03  1.00000000e+00]]
H1 Det: 1.2328072607542486
255.0 255.0
255.0
(150, 200)
[[ 7.25054672e-01 -4.82082378e-02  2.82871452e+01]
 [-3.31154185e-02  1.04682112e+00 -2.66223329e+00]
 [ 1.79312787e-05 -2.58080756e-04  1.00000000e+00]]
H1 Det: 0.9327678990364926
255.0 255.0
255.0
(150, 200)
[[ 9.53551323e-01 -1.10221992e-02  2.65673942e+00]
 [ 6.08012128e-03  9.74569845e-01  1.30934225e-01]
 [-2.11915070e-04 -2.09224395e-04  1.00000000e+00]]
H1 Det: 0.8674192210448879
255.0 255.0
255.0
(150, 200)
[[ 1.07055752e+00  8.08075683e-02 -9.40099966e+00]
 [-5.36048183e-02  1.04801810e+00  5.29392592e+00]
 [ 2.62052535e-04  1.42830992e-04  1.00000000e+00]]
H1 Det: 1.128251776606258
255.0 255.0
255.0
(150, 200)
[[ 9.65713839e-01  3.19659954e-02 -6.12394022e-01]
 [-5.16702611e-02  9.72917058e-01  5.81969193e+00]
 [ 2.48412381e-04 -1.10174441e

 [-4.69115565e-05  1.04916587e-04  1.00000000e+00]]
H1 Det: 1.0152207299440266
255.0 255.0
255.0
(150, 200)
[[ 1.01025921e+00 -3.31221775e-02 -1.01109004e+00]
 [-4.16021364e-04  9.26438739e-01  2.68891327e+00]
 [ 1.25229193e-04 -4.64723248e-04  1.00000000e+00]]
H1 Det: 0.9372978652491168
255.0 255.0
255.0
(150, 200)
[[ 1.04769431e+00 -1.08998363e-01 -1.80110219e-01]
 [ 1.83279106e-02  1.00349417e+00 -1.91352252e+00]
 [ 3.17628683e-04 -8.61986110e-04  1.00000000e+00]]
H1 Det: 0.9858041952871073
255.0 255.0
255.0
(150, 200)
[[ 1.03776413e+00  1.08497540e-01 -2.85397271e+00]
 [ 5.94232566e-02  1.08591727e+00 -7.75654472e+00]
 [ 4.52752100e-04 -1.65033733e-04  1.00000000e+00]]
H1 Det: 1.1042982587139827
255.0 255.0
255.0
(150, 200)
[[ 1.01744541e+00  9.41909597e-03 -2.17510277e+00]
 [-4.76836434e-03  9.91369103e-01  1.31559896e+00]
 [ 2.20744886e-04 -4.19130725e-06  1.00000000e+00]]
H1 Det: 1.1144502447105085
255.0 255.0
255.0
(150, 200)
[[ 8.99169483e-01 -3.75322043e-02  7.49182700e+00]
 

[[ 9.56966321e-01 -1.02177457e-02  1.80335062e+00]
 [-1.89350800e-02  9.58697561e-01  2.37417184e+00]
 [-3.46065483e-04 -2.11953242e-04  1.00000000e+00]]
H1 Det: 0.8586152975936489
255.0 255.0
255.0
(150, 200)
[[ 1.03869485e+00  2.41031662e-02 -3.04965912e+00]
 [ 1.45820336e-02  1.03565083e+00 -2.16245003e+00]
 [-2.31926982e-04 -1.04755907e-04  1.00000000e+00]]
H1 Det: 0.9225157258092812
255.0 255.0
255.0
(150, 200)
[[ 1.00458978e+00  3.91552541e-02 -3.49041904e+00]
 [-4.09470455e-02  9.91374442e-01  4.95679305e+00]
 [-1.22165098e-05  8.84326023e-06  1.00000000e+00]]
H1 Det: 0.997440506402711
255.0 255.0
255.0
(150, 200)
[[ 9.98919616e-01  4.56914922e-02 -3.11496270e+00]
 [-5.13752484e-02  1.00880981e+00  4.96519417e+00]
 [-2.27177254e-05  6.34783888e-05  1.00000000e+00]]
H1 Det: 1.0071018042129407
255.0 255.0
255.0
(150, 200)
[[ 9.96143123e-01  8.01149365e-02 -4.75881407e+00]
 [-5.26243073e-02  1.02583588e+00  4.52237286e+00]
 [-1.00386604e-04  2.82456618e-04  1.00000000e+00]]
H1 Det:

255.0 255.0
255.0
(150, 200)
[[ 1.06664496e+00 -1.08038463e-03 -4.59519528e+00]
 [-5.32359749e-02  9.48901726e-01  8.41939167e+00]
 [ 3.88108069e-04 -2.48633983e-04  1.00000000e+00]]
H1 Det: 1.0554671568109304
255.0 255.0
255.0
(150, 200)
[[ 1.03057316e+00  4.63297136e-03 -2.17192647e+00]
 [-2.42282133e-03  1.01301462e+00  1.74623286e-01]
 [ 1.34583440e-04 -6.25903474e-06  1.00000000e+00]]
H1 Det: 1.0442942184043407
255.0 255.0
255.0
(150, 200)
[[ 9.75489334e-01 -3.37378340e-03  1.06511018e+00]
 [-1.32766435e-02  9.84022020e-01  1.36716675e+00]
 [ 7.90879241e-06 -6.51449611e-05  1.00000000e+00]]
H1 Det: 1.0024573571317064
255.0 255.0
255.0
(150, 200)
[[ 1.02999876e+00  8.67485386e-03 -2.02090382e+00]
 [ 8.77077151e-03  1.01701782e+00 -9.64800290e-01]
 [ 1.45769115e-04 -6.24531655e-06  1.00000000e+00]]
H1 Det: 1.050317961979878
255.0 255.0
255.0
(150, 200)
[[ 1.02550106e+00  1.39822818e-02 -1.83347074e+00]
 [ 9.81729061e-03  1.02595513e+00 -1.28600220e+00]
 [ 1.14420622e-04  1.85477058e

[[ 7.67547745e-01 -1.86605688e-01  1.43420923e+01]
 [-5.08558317e-02  7.66512658e-01  7.73251966e+00]
 [-7.14518363e-04 -1.19804641e-03  1.00000000e+00]]
H1 Det: 0.7886404280358318
255.0 255.0
255.0
(150, 200)
[[ 1.45668710e+00  7.46947323e-02 -2.99361005e+01]
 [ 2.38844586e-01  1.09243421e+00 -2.00689342e+01]
 [ 1.22685974e-03 -1.24378192e-03  1.00000000e+00]]
H1 Det: 1.2494507191183242
255.0 255.0
255.0
(150, 200)
[[ 9.55772278e-01  2.68951716e-02 -4.43918636e-01]
 [-3.69240613e-02  9.54644640e-01  4.38825716e+00]
 [-2.35135366e-05 -3.43500387e-04  1.00000000e+00]]
H1 Det: 0.9148382916372068
255.0 255.0
255.0
(150, 200)
[[ 1.01564372e+00  3.48236683e-02 -3.28561546e+00]
 [-3.49656276e-02  1.01556382e+00  3.08550747e+00]
 [ 3.52730355e-05 -3.16981760e-04  1.00000000e+00]]
H1 Det: 0.9457114076159695
255.0 255.0
255.0
(150, 200)
[[ 1.01533827e+00 -1.84910066e-02  5.05292815e-01]
 [ 1.45249115e-03  1.00270850e+00  7.63073247e-03]
 [ 6.16628183e-05 -2.37353553e-04  1.00000000e+00]]
H1 Det

[[ 1.12375330e+00  7.62158137e-04 -7.61318638e+00]
 [ 1.71734732e-02  1.04982793e+00 -1.15830780e+00]
 [ 3.87501609e-04  5.67101530e-04  1.00000000e+00]]
H1 Det: 1.303809100671684
255.0 255.0
255.0
(150, 200)
[[ 1.18533642e+00 -4.87510279e-02 -5.48160735e+00]
 [ 7.09994902e-02  1.09527010e+00 -7.81473313e+00]
 [ 1.03862774e-03  6.87837353e-04  1.00000000e+00]]
H1 Det: 1.7138050192139622
255.0 255.0
255.0
(150, 200)
[[ 1.06476482e+00  7.13327948e-02 -7.27923886e+00]
 [-2.50144801e-02  1.04708245e+00  1.97056481e+00]
 [ 3.07034510e-04  1.12095033e-04  1.00000000e+00]]
H1 Det: 1.1188494780693
255.0 255.0
255.0
(150, 200)
[[ 9.51268160e-01 -5.36655470e-03  1.18348023e+00]
 [-4.37781393e-02  9.30887707e-01  6.10705323e+00]
 [ 2.27335998e-04 -3.44029120e-04  1.00000000e+00]]
H1 Det: 0.9924725627365901
255.0 255.0
255.0
(150, 200)
[[ 9.55747439e-01  1.76672840e-02 -3.92209034e-01]
 [-2.29040848e-02  9.79733828e-01  1.70074917e+00]
 [-1.17779684e-04 -1.84458252e-04  1.00000000e+00]]
H1 Det: 0.

255.0 255.0
255.0
(150, 200)
[[ 6.15977678e-01 -1.04988708e-01  2.67573408e+01]
 [ 3.52649669e-02  7.80932430e-01 -3.26385407e+00]
 [-8.99954517e-04 -1.08787929e-03  1.00000000e+00]]
H1 Det: 0.7075743393013275
255.0 255.0
255.0
(150, 200)
[[ 1.43881997e+00  1.92024710e-02 -1.52538941e+01]
 [ 6.60318810e-02  1.26585615e+00 -7.15657180e+00]
 [ 1.37099339e-03 -2.03809577e-04  1.00000000e+00]]
H1 Det: 1.3050941360977193
255.0 255.0
255.0
(150, 200)
[[ 9.72718024e-01  1.99756268e-02 -1.31840779e+00]
 [-4.36295908e-02  9.66331952e-01  5.27646232e+00]
 [-9.42196171e-05 -1.39194693e-04  1.00000000e+00]]
H1 Det: 0.9414164775452577
255.0 255.0
255.0
(150, 200)
[[ 1.00297063e+00  2.14977811e-02 -1.62809647e+00]
 [-1.03391072e-02  1.00820525e+00  6.95102504e-01]
 [-7.35456676e-05 -1.07648689e-04  1.00000000e+00]]
H1 Det: 0.9521240859390765
best_err =  14.422478
255.0 255.0
255.0
(150, 200)
[[ 1.01297524e+00  1.17183286e-02 -1.16917634e+00]
 [-3.07025177e-03  1.01462584e+00  5.73876668e-02]
 [-2.18

[[ 9.37012565e-01 -7.06866050e-02  6.96925417e+00]
 [ 9.23511105e-03  9.44332255e-01 -9.14961871e-02]
 [-3.76979433e-04  3.89554620e-05  1.00000000e+00]]
H1 Det: 0.903052025791522
255.0 255.0
255.0
(150, 200)
[[ 9.98954982e-01 -4.21815723e-02 -8.27748699e-02]
 [ 7.78051508e-02  9.56662598e-01 -6.62420110e+00]
 [-5.52213411e-04 -5.48417255e-05  1.00000000e+00]]
H1 Det: 0.8654708251468306
255.0 255.0
255.0
(150, 200)
[[ 1.03768041e+00 -3.07435159e-02  3.73310663e+00]
 [ 6.17511279e-02  1.06567433e+00 -7.42012662e+00]
 [-2.79292058e-04  9.30505385e-05  1.00000000e+00]]
H1 Det: 0.9602512416361566
255.0 255.0
255.0
(150, 200)
[[ 1.00173663e+00  2.14041913e-02 -1.87382801e+00]
 [-2.32246190e-02  9.96176577e-01  2.50152778e+00]
 [-3.54231777e-05  3.88385365e-05  1.00000000e+00]]
H1 Det: 0.9982400196974109
255.0 255.0
255.0
(150, 200)
[[ 9.97848444e-01  1.49824107e-02 -8.45342396e-01]
 [-1.22498002e-02  1.00432577e+00  9.41073532e-01]
 [-3.13738147e-05  4.31748937e-05  1.00000000e+00]]
H1 Det:

255.0 255.0
255.0
(150, 200)
[[ 9.88694515e-01  1.48077138e-01 -6.07769485e+00]
 [-8.68970285e-02  1.12137076e+00  4.05245547e+00]
 [-9.55101542e-04  4.33471819e-04  1.00000000e+00]]
H1 Det: 0.8571467529960397
255.0 255.0
255.0
(150, 200)
[[ 1.05487477e+00  2.39698510e-02 -4.70442714e+00]
 [-1.07566575e-02  1.03613999e+00  1.32555457e+00]
 [ 1.83881023e-04  1.37094605e-04  1.00000000e+00]]
H1 Det: 1.0939731669622559
255.0 255.0
255.0
(150, 200)
[[ 1.04319202e+00  3.95319481e-02 -3.44576153e+00]
 [ 1.57499114e-02  1.05589769e+00 -2.34029718e+00]
 [ 2.67809039e-04  4.76839371e-04  1.00000000e+00]]
H1 Det: 1.206618822997394
255.0 255.0
255.0
(150, 200)
[[ 9.17033789e-01 -1.49757968e-02  4.12142135e+00]
 [-4.47506094e-02  9.25409183e-01  5.83168256e+00]
 [ 2.13212662e-05  7.63349954e-05  1.00000000e+00]]
H1 Det: 1.0225561503224874
255.0 255.0
255.0
(150, 200)
[[ 9.80878091e-01 -1.09047884e-03 -6.09973555e-02]
 [-7.27151261e-03  9.83802423e-01  4.14938846e-01]
 [-9.04262405e-05  5.62323867e

[[ 9.96852600e-01  3.67616689e-03 -1.15120042e-01]
 [-1.20548391e-02  9.97452837e-01  1.11853892e+00]
 [ 3.37102838e-05  1.03095411e-04  1.00000000e+00]]
H1 Det: 1.0490262222526703
255.0 255.0
255.0
(150, 200)
[[ 1.01035281e+00  1.70890251e-02 -1.57476904e+00]
 [-9.35356566e-03  1.01480689e+00  6.59712927e-01]
 [ 7.88696453e-05  1.66405272e-04  1.00000000e+00]]
H1 Det: 1.075767273078764
255.0 255.0
255.0
(150, 200)
[[ 9.74006492e-01 -5.58132302e-02  4.14526407e+00]
 [ 3.02036871e-02  9.45628373e-01 -1.52728125e+00]
 [-7.96130756e-05 -2.36026543e-04  1.00000000e+00]]
H1 Det: 0.9226585669954032
255.0 255.0
255.0
(150, 200)
[[ 9.06664856e-01 -1.11987016e-02  4.95009957e+00]
 [ 1.83694085e-02  9.83234866e-01 -2.89588356e+00]
 [-6.02896553e-04 -2.66866327e-05  1.00000000e+00]]
H1 Det: 0.8253296480226592
255.0 255.0
255.0
(150, 200)
[[ 1.04736050e+00 -5.69910180e-02  5.58221691e-01]
 [ 6.21621616e-02  9.66710305e-01 -4.25025748e+00]
 [-3.96725607e-04 -3.40228356e-04  1.00000000e+00]]
H1 Det:

[[ 9.76102022e-01  4.33502651e-02 -3.83045282e+00]
 [-7.53277535e-02  9.36127681e-01  9.29659732e+00]
 [-2.64154050e-04  1.26566437e-04  1.00000000e+00]]
H1 Det: 0.9474033533724439
255.0 255.0
255.0
(150, 200)
[[ 9.36999650e-01  3.77787106e-03 -3.97058189e-01]
 [-3.40601029e-02  8.94004492e-01  5.50830798e+00]
 [-4.41599338e-04 -4.09443890e-04  1.00000000e+00]]
H1 Det: 0.795584186785656
255.0 255.0
255.0
(150, 200)
[[ 1.15768556e+00 -1.01919078e-01 -5.56483353e+00]
 [-1.65526114e-02  1.02897135e+00  2.23193270e+00]
 [ 3.42300077e-04 -1.03489944e-03  1.00000000e+00]]
H1 Det: 0.9499268282493039
255.0 255.0
255.0
(150, 200)
[[ 1.23357287e+00  4.51524576e-01 -3.07906387e+01]
 [ 1.31709649e-01  1.51698018e+00 -2.95384437e+01]
 [ 4.15796694e-04  2.15000882e-03  1.00000000e+00]]
H1 Det: 1.800428276241573
255.0 255.0
229.0
(150, 200)
[[ 9.72277742e-01 -1.07567136e-02  9.81249550e-01]
 [-2.98470423e-02  9.72018506e-01  4.02086467e+00]
 [-1.82535722e-04  7.22718388e-06  1.00000000e+00]]
H1 Det: 

[[ 1.05124599e+00  1.96770293e-02 -2.46538678e+00]
 [-3.28684755e-02  1.02337565e+00  3.73798675e+00]
 [ 5.97845345e-04  1.79288470e-04  1.00000000e+00]]
H1 Det: 1.268234394480031
255.0 255.0
255.0
(150, 200)
[[ 9.98067046e-01  1.47708150e-02 -1.77756830e+00]
 [-1.99470789e-04  1.01983369e+00 -1.06318540e+00]
 [ 6.79703049e-04 -3.19807173e-04  1.00000000e+00]]
H1 Det: 1.2920104634316172
255.0 255.0
255.0
(150, 200)
[[ 8.93530291e-01  1.52252314e-02  3.14412857e+00]
 [-2.64176870e-02  9.52204828e-01  2.65685512e+00]
 [ 7.15511921e-05 -2.99574932e-04  1.00000000e+00]]
H1 Det: 1.1004709721641797
255.0 255.0
255.0
(150, 200)
[[ 1.06816170e+00 -2.12187515e-03 -3.51740035e+00]
 [-3.10887113e-02  9.93145882e-01  4.36608583e+00]
 [ 2.80690480e-04  3.15524635e-04  1.00000000e+00]]
H1 Det: 1.166846272933287
255.0 255.0
255.0
(150, 200)
[[ 9.56219416e-01 -3.32503293e-02  3.39908709e+00]
 [-1.59811598e-02  9.45934000e-01  2.63562666e+00]
 [-1.65230249e-04 -1.93525875e-04  1.00000000e+00]]
H1 Det: 

[[ 9.92157688e-01  3.11301843e-02 -1.66764374e+00]
 [-2.33307663e-02  1.01055233e+00  2.10945300e+00]
 [-8.80200322e-05  2.64304908e-04  1.00000000e+00]]
H1 Det: 1.0377393590706636
255.0 255.0
255.0
(150, 200)
[[ 9.79981337e-01  2.73738167e-03  1.41000125e-01]
 [-2.04026087e-02  9.69716310e-01  2.62497801e+00]
 [-7.72412347e-05  2.72303380e-05  1.00000000e+00]]
H1 Det: 0.9861633138211683
255.0 255.0
255.0
(150, 200)
[[ 1.01422908e+00  2.35230174e-02 -1.86368803e+00]
 [-6.87642155e-03  1.02293836e+00  9.87773892e-02]
 [-3.95914501e-05  1.80855040e-04  1.00000000e+00]]
H1 Det: 1.0232077696393351
255.0 255.0
255.0
(150, 200)
[[ 1.01278739e+00  4.70610922e-02 -2.75957723e+00]
 [ 1.08818233e-02  1.06905258e+00 -2.66796735e+00]
 [-1.43708995e-04  5.56935005e-04  1.00000000e+00]]
H1 Det: 1.0832931059631916
255.0 255.0
255.0
(150, 200)
[[ 1.03684784e+00  7.60966229e-02 -5.62881210e+00]
 [-6.33726016e-02  1.07397949e+00  4.65795178e+00]
 [-1.51542211e-04  1.01065458e-03  1.00000000e+00]]
H1 Det

255.0 255.0
255.0
(150, 200)
[[ 8.52682900e-01 -4.86037820e-02  9.04583059e+00]
 [-1.60425573e-02  9.02316708e-01  2.58771096e+00]
 [-3.50884147e-04 -5.46497062e-04  1.00000000e+00]]
H1 Det: 0.7800001902673529
255.0 255.0
255.0
(150, 200)
[[ 1.19410562e+00  2.04931766e-03 -6.40098086e+00]
 [ 1.50507493e-01  1.14833904e+00 -1.54690436e+01]
 [ 3.45881881e-04 -1.74625117e-04  1.00000000e+00]]
H1 Det: 1.068915166993826
255.0 255.0
255.0
(150, 200)
[[ 1.03820271e+00 -3.88497465e-02  2.63337853e+00]
 [ 2.44821332e-02  1.03630661e+00 -3.43947762e+00]
 [ 4.85985716e-04  3.33110654e-05  1.00000000e+00]]
H1 Det: 1.1498397890322838
255.0 255.0
255.0
(150, 200)
[[ 9.19099590e-01 -2.83603893e-02  4.82863646e+00]
 [-3.54410397e-02  9.36729488e-01  3.68537459e+00]
 [-2.64247275e-04 -3.00669487e-04  1.00000000e+00]]
H1 Det: 0.8622352984790892
255.0 255.0
255.0
(150, 200)
[[ 9.89923546e-01  8.52050353e-03 -1.72664555e+00]
 [ 1.25988396e-02  9.75787174e-01 -1.13009163e+00]
 [-3.75713168e-04 -4.10802268e

[[ 1.08167004e+00  1.01240319e-02 -2.86695256e+00]
 [ 4.33259300e-02  1.07532220e+00 -4.96788738e+00]
 [-1.63005549e-04  8.01697874e-04  1.00000000e+00]]
H1 Det: 1.1511810823625646
255.0 255.0
255.0
(150, 200)
[[ 9.92797120e-01  1.48310031e-02 -1.57962886e+00]
 [-3.08843729e-02  9.79305913e-01  3.84605963e+00]
 [-8.44001163e-06 -1.09351733e-04  1.00000000e+00]]
H1 Det: 0.97310880753004
best_err =  13.65913
255.0 255.0
255.0
(150, 200)
[[ 9.73349603e-01  3.64578949e-02 -1.53960096e+00]
 [-2.53430869e-02  1.00553030e+00  1.41185437e+00]
 [-1.69233170e-04  4.23261914e-06  1.00000000e+00]]
H1 Det: 0.9530434231997162
255.0 255.0
255.0
(150, 200)
[[ 1.03412931e+00  1.50460342e-03 -1.11215390e+00]
 [-5.01833643e-03  1.01912678e+00  9.03317893e-01]
 [ 3.38576365e-05  8.70722119e-05  1.00000000e+00]]
H1 Det: 1.004387680196146
best_err =  13.635268
255.0 255.0
255.0
(150, 200)
[[ 9.67684090e-01 -8.55599233e-03  1.39694852e+00]
 [-6.87903606e-03  9.64857049e-01  1.36860381e+00]
 [-1.28482824e-04 

 [-6.75226803e-04 -3.30705426e-04  1.00000000e+00]]
H1 Det: 0.7668180626572993
255.0 255.0
255.0
(150, 200)
[[ 1.16860525e+00  7.45421464e-02 -1.11853530e+01]
 [ 3.70333009e-02  1.13872159e+00 -5.81207402e+00]
 [-3.93453814e-04  3.42151325e-04  1.00000000e+00]]
H1 Det: 1.0162614447706149
255.0 255.0
255.0
(150, 200)
[[ 9.93888400e-01  3.29833634e-02 -7.72340889e-01]
 [-2.82111650e-02  1.05097621e+00  6.71167132e-01]
 [-3.72819504e-04  6.32923476e-04  1.00000000e+00]]
H1 Det: 1.061753653371972
255.0 255.0
255.0
(150, 200)
[[ 1.01149825e+00 -5.37385022e-02  3.87661106e+00]
 [ 5.13782207e-03  9.57290709e-01  2.81659813e+00]
 [ 5.73964275e-05 -2.49821880e-05  1.00000000e+00]]
H1 Det: 1.0282266250300096
255.0 255.0
255.0
(150, 200)
[[ 9.94947772e-01  8.91662964e-04 -8.48835885e-01]
 [-1.71400313e-02  9.56523422e-01  2.90491273e+00]
 [ 9.08944850e-05 -3.36472383e-04  1.00000000e+00]]
H1 Det: 0.9527477561448232
255.0 255.0
255.0
(150, 200)
[[ 9.56759689e-01  2.32617581e-02  1.28533358e+00]
 [

 [ 7.49146290e-05  8.10768609e-04  1.00000000e+00]]
H1 Det: 1.2791652824746493
255.0 255.0
255.0
(150, 200)
[[ 9.70427157e-01 -2.92316113e-02  3.50233962e+00]
 [-1.18244435e-01  8.82753812e-01  2.00165480e+01]
 [ 1.52506290e-04  1.45291695e-04  1.00000000e+00]]
H1 Det: 1.0869689789950538
255.0 255.0
255.0
(150, 200)
[[ 9.87203534e-01  3.84790198e-02 -2.63601523e+00]
 [-2.11670501e-02  9.84757007e-01  1.75612875e+00]
 [ 2.18477974e-04 -4.15108754e-05  1.00000000e+00]]
H1 Det: 1.0582965091060592
255.0 255.0
255.0
(150, 200)
[[ 9.92039881e-01  8.74892117e-03 -1.47161702e-01]
 [-1.48417342e-02  9.96619116e-01  1.12589140e+00]
 [ 1.73127691e-04 -4.57794553e-05  1.00000000e+00]]
H1 Det: 1.0465429497198588
255.0 255.0
255.0
(150, 200)
[[ 1.00908507e+00  1.28654068e-02 -5.47818935e-01]
 [ 1.43132885e-02  1.04234681e+00 -3.13241165e+00]
 [ 9.26567016e-05  7.26925119e-05  1.00000000e+00]]
H1 Det: 1.0519108331637426
255.0 255.0
234.0
(150, 200)
[[ 9.86717095e-01  1.87538235e-02 -3.70703727e-01]
 

255.0 255.0
255.0
(150, 200)
[[ 9.74188674e-01 -5.74309875e-03  1.24120592e+00]
 [ 1.79199833e-03  9.81490092e-01 -3.03571699e-02]
 [-2.17826095e-04 -1.28233349e-04  1.00000000e+00]]
H1 Det: 0.9018209102205565
255.0 255.0
255.0
(150, 200)
[[ 9.81821261e-01  4.77698499e-03  1.08216817e-01]
 [-4.10883092e-03  9.92422697e-01  2.39040800e-01]
 [-3.45602225e-04 -1.29473547e-04  1.00000000e+00]]
H1 Det: 0.8787960673682982
255.0 255.0
255.0
(150, 200)
[[ 1.09697134e+00  2.96385363e-02 -5.63491461e+00]
 [ 4.18971491e-02  1.06078671e+00 -4.01185330e+00]
 [-1.54352795e-04  2.78385882e-04  1.00000000e+00]]
H1 Det: 1.0217462985049806
255.0 255.0
255.0
(150, 200)
Estimated homography : 
 [[-8.01957924e-01 -6.04594750e-01  2.25489596e+02]
 [ 6.00299906e-01 -7.99520399e-01  7.47538285e+01]
 [ 2.88565546e-04 -5.81974434e-04  1.07697460e+00]]
Press key to cont.
Reading image to align :  D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040159422.png
Aligning images ...
[[ 9.21733874e-01  6.72640874e-02 -9

 [-1.40934537e-04  1.89501011e-04  1.00000000e+00]]
H1 Det: 1.0066468907885686
255.0 255.0
255.0
(150, 200)
[[ 9.71713139e-01 -6.52155077e-03  1.97526675e+00]
 [ 1.09477899e-03  9.83267182e-01  1.64692559e-01]
 [-1.86755917e-04  5.33817378e-05  1.00000000e+00]]
H1 Det: 0.9621684719379835
255.0 255.0
255.0
(150, 200)
[[ 9.03871398e-01 -7.91480928e-02  6.71849227e+00]
 [-9.07845165e-02  9.85790462e-01  4.74369396e+00]
 [-2.58357539e-04 -6.54913679e-04  1.00000000e+00]]
H1 Det: 0.8888580124282625
255.0 255.0
255.0
(150, 200)
[[ 8.21577514e-01  1.14518539e-03  5.35637560e+00]
 [-6.61640801e-02  9.16516853e-01  4.93827417e+00]
 [-1.55265905e-03 -1.97855407e-04  1.00000000e+00]]
H1 Det: 0.6769114268021941
255.0 255.0
255.0
(150, 200)
[[ 1.31918039e+00  8.31185141e-02 -1.49040304e+01]
 [ 1.43122516e-01  1.33434042e+00 -1.89860149e+01]
 [-6.54940733e-04  8.62129476e-04  1.00000000e+00]]
H1 Det: 1.18872562528444
255.0 255.0
255.0
(150, 200)
[[ 1.04668634e+00 -9.18433872e-02 -1.92690488e-01]
 [ 

[[ 1.00009737e+00  4.06929683e-03 -5.23875815e-01]
 [-2.52126241e-03  9.95148383e-01  4.52456206e-01]
 [-1.36964973e-05  2.91123073e-05  1.00000000e+00]]
H1 Det: 1.0043561294032037
255.0 255.0
255.0
(150, 200)
[[ 1.01569323e+00  3.26633224e-03 -8.67061744e-01]
 [ 4.41637437e-03  1.00725494e+00 -4.07452676e-01]
 [ 5.88513475e-05  3.80123628e-05  1.00000000e+00]]
H1 Det: 1.027571318170073
255.0 255.0
204.35938
(150, 200)
Estimated homography : 
 [[-7.38215291e-01 -6.72732654e-01  2.24037680e+02]
 [ 6.71128573e-01 -7.43615172e-01  6.39657589e+01]
 [ 6.93339497e-05  2.99460587e-05  9.85822843e-01]]
Press key to cont.
Reading image to align :  D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040159422.png
Aligning images ...
[[ 9.67113412e-01 -7.71138179e-02  4.71074046e+00]
 [-2.67267734e-02  9.57194960e-01  2.86476325e+00]
 [ 2.85067903e-05 -5.45895349e-04  1.00000000e+00]]
H1 Det: 0.9251014035170075
best_err =  9999
255.0 255.0
255.0
(150, 200)
[[ 1.09482081e+00  1.21214917e-01 -8.45963159

H1 Det: 0.9564016855131815
255.0 255.0
255.0
(150, 200)
[[ 1.00641878e+00  7.55715556e-02 -4.95526723e+00]
 [-5.74888559e-02  1.05121888e+00  4.58361365e+00]
 [-9.52840902e-05  2.14906897e-04  1.00000000e+00]]
H1 Det: 1.0146001104952829
255.0 255.0
255.0
(150, 200)
[[ 1.04810580e+00  2.35988778e-03 -3.91562215e+00]
 [-5.90944344e-02  9.44764472e-01  8.58427705e+00]
 [ 3.67415133e-04 -4.29846983e-04  1.00000000e+00]]
H1 Det: 1.0100214055007044
255.0 255.0
255.0
(150, 200)
[[ 9.99932323e-01  1.20173591e-02  3.46618892e-01]
 [ 1.67645363e-02  1.04304062e+00 -3.95074525e+00]
 [ 2.28404363e-04 -1.41196662e-04  1.00000000e+00]]
H1 Det: 1.0525600047792647
255.0 255.0
255.0
(150, 200)
[[ 1.02158891e+00 -8.30991591e-03 -6.27162529e-01]
 [-7.87056796e-03  1.03466864e+00 -4.61438203e-01]
 [ 2.74212718e-05  1.29517403e-04  1.00000000e+00]]
H1 Det: 1.0570201989806935
255.0 255.0
255.0
(150, 200)
[[ 1.06518777e+00  8.18461314e-03 -2.94747967e+00]
 [ 1.16673278e-02  1.06103044e+00 -2.24592140e+00]
 [

Reading image to align :  D:\Images\A70\Image_8419A5/鏡筒_A_IPI_4_20190108_040159422.png
Aligning images ...
[[ 1.07525955e+00  1.28568653e-01 -1.01090649e+01]
 [-5.27923683e-02  1.11946968e+00  2.63506488e+00]
 [ 2.22168880e-04  5.46648632e-04  1.00000000e+00]]
H1 Det: 1.2118402916391229
best_err =  9999
255.0 255.0
255.0
(150, 200)
[[ 1.07272296e+00  9.22249504e-02 -1.00841025e+01]
 [-1.14337353e-01  1.01135679e+00  1.41556632e+01]
 [ 7.02694396e-04  3.07439791e-04  1.00000000e+00]]
H1 Det: 1.3320793986011878
255.0 255.0
255.0
(150, 200)
[[ 6.42169041e-01  4.66758491e-02  3.71238971e+00]
 [-1.54357793e-01  6.64397244e-01  1.82206564e+01]
 [-1.97459359e-03 -8.53116647e-04  1.00000000e+00]]
H1 Det: 0.5961349729095469
255.0 255.0
255.0
(150, 200)
[[ 1.93900928e+00  2.33150201e-01 -2.91692138e+01]
 [ 5.75521965e-02  1.82679121e+00 -1.15652685e+01]
 [ 3.81623433e-03  3.63685128e-03  1.00000000e+00]]
H1 Det: 2.2636796392870404
[[ 9.72670361e-01  1.48392874e-02  8.45403876e-01]
 [-2.13412186e

255.0 255.0
255.0
(150, 200)
[[ 9.45203439e-01 -7.47975469e-02  5.74794302e+00]
 [ 8.05843383e-02  9.87921323e-01 -1.32983755e+01]
 [-6.39873531e-04 -1.36485610e-03  1.00000000e+00]]
H1 Det: 0.7240727505712835
255.0 255.0
255.0
(150, 200)
[[ 9.74881973e-01 -5.63345870e-02  4.89014674e+00]
 [-7.69426245e-04  9.78308625e-01 -5.80362604e-01]
 [-8.19022086e-04 -1.35114294e-03  1.00000000e+00]]
H1 Det: 0.6928103361651798
255.0 255.0
255.0
(150, 200)
[[ 1.00055073e+00 -9.77392660e-03  9.27144734e-01]
 [-4.54238655e-03  1.02497140e+00 -9.04122022e-01]
 [ 8.57823341e-06  8.16137696e-05  1.00000000e+00]]
H1 Det: 1.0255568956220522
255.0 255.0
255.0
(150, 200)
[[ 9.51589773e-01 -1.82410253e-02  2.38298088e+00]
 [-1.35222578e-02  9.57376084e-01  1.84455622e+00]
 [-1.70633772e-04 -1.21909681e-04  1.00000000e+00]]
H1 Det: 0.9346880110400503
255.0 255.0
255.0
(150, 200)
[[ 9.22152841e-01 -1.30618470e-02  2.85689908e+00]
 [-3.57784955e-03  9.33678651e-01  1.17298224e+00]
 [-5.61961668e-04 -2.29530250

[[ 1.12125094e+00 -1.36769548e-01 -3.73720027e+00]
 [ 7.45695707e-02  9.16719209e-01 -3.24299720e+00]
 [ 4.62305834e-04 -1.00510879e-03  1.00000000e+00]]
H1 Det: 0.9698981717601222
255.0 255.0
255.0
(150, 200)
[[ 1.01344205e+00 -5.06822286e-03 -1.43494721e+00]
 [-9.97576132e-03  9.81942364e-01  2.03360742e+00]
 [ 1.13653547e-04 -1.84578211e-04  1.00000000e+00]]
H1 Det: 0.9956278606796014
best_err =  16.251099
255.0 255.0
255.0
(150, 200)
[[ 9.26680443e-01 -2.03168111e-02  3.49929982e+00]
 [-6.55286669e-03  9.22583831e-01  1.88447721e+00]
 [-1.22475830e-04 -5.10733351e-04  1.00000000e+00]]
H1 Det: 0.8523679225905687
255.0 255.0
255.0
(150, 200)
[[ 8.87495269e-01 -1.15494415e-01  7.70201738e+00]
 [-2.76801368e-02  9.03149697e-01  3.19208854e+00]
 [-6.24268530e-04 -1.10343636e-03  1.00000000e+00]]
H1 Det: 0.6872455275390726
255.0 255.0
255.0
(150, 200)
[[ 1.13891583e+00  2.75736579e-03 -5.13909728e+00]
 [-8.75546151e-02  1.10466480e+00  7.83311769e+00]
 [ 2.45797541e-04  6.21061251e-04  1

255.0 255.0
255.0
(150, 200)
[[ 9.94660717e-01 -1.64605618e-02  8.28132478e-01]
 [ 1.17581995e-02  9.55949327e-01  6.15746842e-01]
 [-2.78329500e-04  2.40863847e-04  1.00000000e+00]]
H1 Det: 0.9613490761667511
255.0 255.0
255.0
(150, 200)
[[ 9.49404422e-01 -8.89849983e-04  7.02135137e-01]
 [-3.24281583e-02  9.51295447e-01  3.90992285e+00]
 [-2.41311877e-04 -1.41096292e-04  1.00000000e+00]]
H1 Det: 0.903824244902456
255.0 255.0
255.0
(150, 200)
[[ 1.10914838e+00 -2.85328220e-02 -6.95652360e+00]
 [ 4.41981098e-02  9.76698055e-01 -1.91454211e+00]
 [ 2.49123075e-04 -5.76001044e-04  1.00000000e+00]]
H1 Det: 0.980852096411716
255.0 255.0
255.0
(150, 200)
[[ 1.06566475e+00  3.31709645e-02 -5.57659482e+00]
 [ 4.15034726e-03  1.06833300e+00 -2.23815504e+00]
 [ 1.55152833e-04  3.38787512e-05  1.00000000e+00]]
H1 Det: 1.1175240222907712
255.0 255.0
255.0
(150, 200)
[[ 1.00902672e+00 -2.74409126e-03  2.47353702e+00]
 [ 1.60414925e-02  1.03997757e+00 -2.29180057e+00]
 [ 3.40410902e-04  6.24321674e-

255.0 255.0
255.0
(150, 200)
[[ 1.04134529e+00  3.88765870e-02 -3.73986417e+00]
 [-1.05546165e-02  1.06240287e+00 -5.00928879e-01]
 [ 3.22861349e-04  5.60527509e-04  1.00000000e+00]]
H1 Det: 1.2580427167501484
255.0 255.0
255.0
(150, 200)
[[ 1.28737585e+00 -3.07192551e-02 -1.39388213e+01]
 [ 1.02914728e-01  1.15364839e+00 -1.02342200e+01]
 [ 1.02911517e-03  3.19660378e-04  1.00000000e+00]]
H1 Det: 1.5089658277411935
255.0 255.0
255.0
(150, 200)
[[ 7.30641479e-01 -1.22168625e-01  1.75340255e+01]
 [ 5.52302119e-02  8.27715334e-01 -6.95092616e+00]
 [-5.49026807e-04 -1.60721232e-03  1.00000000e+00]]
H1 Det: 0.9194031815486602
255.0 255.0
255.0
(150, 200)
[[ 1.02448122e+00 -1.77677705e-01  7.69266068e+00]
 [ 6.37685650e-02  8.62400476e-01  3.32657378e-01]
 [ 3.85425618e-05 -1.25308310e-03  1.00000000e+00]]
H1 Det: 0.8223121128302489
255.0 255.0
255.0
(150, 200)
[[ 1.36546709e+00  1.01231959e-01 -1.44513034e+01]
 [ 1.49808734e-01  1.39979946e+00 -2.05907598e+01]
 [ 1.71916215e-03 -1.57064262

[[ 7.54315157e-01 -2.76560390e-02  1.15478004e+01]
 [-1.39916742e-01  8.28604930e-01  1.54340257e+01]
 [-7.33988103e-04 -1.57174145e-05  1.00000000e+00]]
H1 Det: 0.8268782678790498
255.0 255.0
255.0
(150, 200)
[[ 1.01962896e+00 -1.07571898e-02  4.39798150e-01]
 [ 2.10352962e-02  1.02609213e+00 -2.65329491e+00]
 [ 8.50916926e-05  1.01025541e-04  1.00000000e+00]]
H1 Det: 1.0466978119732817
255.0 255.0
255.0
(150, 200)
[[ 1.00327980e+00 -4.37785079e-02  1.81444831e+00]
 [ 2.07981099e-02  9.90943270e-01 -1.58074724e+00]
 [-2.77062326e-05  1.26379729e-04  1.00000000e+00]]
H1 Det: 1.0418379707848406
255.0 255.0
255.0
(150, 200)
[[ 1.04707689e+00  6.63362320e-02 -3.99648884e+00]
 [ 1.79668041e-02  1.13644388e+00 -4.79869657e+00]
 [-7.72370055e-05  1.05406109e-03  1.00000000e+00]]
H1 Det: 1.2435863697293448
255.0 255.0
255.0
(150, 200)
[[ 1.00336010e+00 -2.58028971e-02  4.08794774e-01]
 [-1.69271112e-02  9.50271780e-01  3.73102068e+00]
 [-3.42272548e-06  6.33998414e-04  1.00000000e+00]]
H1 Det

255.0 255.0
255.0
(150, 200)
[[ 1.15346847e+00 -7.58419347e-03 -5.86793112e+00]
 [ 8.09673050e-02  1.07989652e+00 -7.46578721e+00]
 [ 3.20033872e-05  2.08635138e-04  1.00000000e+00]]
H1 Det: 1.0767841971849488
255.0 255.0
255.0
(150, 200)
[[ 9.26591493e-01  2.42271008e-02  3.98926896e+00]
 [-2.92531972e-02  1.03814788e+00  2.41884008e-01]
 [-2.97055650e-04  4.79607866e-04  1.00000000e+00]]
H1 Det: 1.0377106601379038
255.0 255.0
255.0
(150, 200)
[[ 1.12107187e+00  3.10452941e-02 -6.80665407e+00]
 [ 2.62466720e-02  1.05322977e+00 -2.49647068e+00]
 [ 3.99870042e-04  3.36372949e-04  1.00000000e+00]]
H1 Det: 1.2282845794899313
255.0 255.0
255.0
(150, 200)
[[ 9.71533502e-01 -3.52281461e-02  1.35312442e+00]
 [-1.14360157e-02  9.42174431e-01  2.77891447e+00]
 [-1.16249378e-04 -2.56443075e-04  1.00000000e+00]]
H1 Det: 0.9158070552074513
255.0 255.0
255.0
(150, 200)
[[ 1.02993518e+00  2.74742020e-02 -2.45113895e+00]
 [ 5.30350752e-03  1.08247341e+00 -2.91510770e+00]
 [-1.98091424e-04  3.31948319

255.0 255.0
255.0
(150, 200)
[[ 9.39285224e-01 -2.24082557e-02  5.12043029e+00]
 [-7.28072551e-03  9.92539856e-01  1.22018113e-01]
 [-6.94535697e-05  4.85393379e-04  1.00000000e+00]]
H1 Det: 1.0990494286019317
255.0 255.0
255.0
(150, 200)
[[ 9.94227964e-01 -7.16184713e-03  4.94136450e-01]
 [ 3.67403643e-03  9.99641440e-01 -6.23995734e-01]
 [-6.53397599e-05  4.38951756e-04  1.00000000e+00]]
H1 Det: 1.0926781179534957
255.0 255.0
255.0
(150, 200)
[[ 1.14332894e+00  3.28043218e-02 -7.70225053e+00]
 [ 4.13493587e-02  1.09387345e+00 -4.95807198e+00]
 [ 6.53165134e-04  5.52807139e-04  1.00000000e+00]]
H1 Det: 1.3742123553329275
255.0 255.0
255.0
(150, 200)
[[ 9.30670860e-01 -4.22339306e-02  5.00238245e+00]
 [-2.77530468e-02  9.21762868e-01  4.36208296e+00]
 [-2.55667862e-04 -2.90821653e-04  1.00000000e+00]]
H1 Det: 0.8591327230673044
255.0 255.0
255.0
(150, 200)
[[ 8.83536156e-01 -2.26974644e-02  5.29665070e+00]
 [-1.86854695e-03  9.42665214e-01 -6.72269561e-01]
 [-9.49624939e-04 -2.36871273

In [452]:
cv2.__version__
#imReg = cv2.warpAffine(im,h[:2,:],(sz[1],sz[0]))        
h

(array([[128, 126, 128, ...,  86,  88,  90],
        [134, 129, 133, ...,  92,  94,  94],
        [133, 122, 126, ...,  86,  88,  94],
        ...,
        [ 97, 103,  99, ..., 131, 132, 130],
        [ 99,  99, 101, ..., 132, 140, 143],
        [103, 102, 102, ..., 134, 138, 138]], dtype=uint8),
 array([[ 1.00059380e+00, -4.92590202e-04, -1.02109904e-03],
        [ 4.67753625e-05,  1.00104664e+00, -1.20936807e-01],
        [-3.72236765e-05,  5.54675533e-04,  9.69863400e-01]]))